### ISSUE TITLE
Set the app to be detected as a game

### ISSUE THREAD

**Issue by YahirAguilera** [gianxddddd/HackerSim#2]

**Comment by gianxddddd** [comment]
Correct me if I am wrong but, the key `android:isGame` is set to true in the AndroidManifest. That's clearly you're phone who's not detecting HackerSim as a game.

**Comment by YahirAguilera** [comment]
i don't think is my phone, it doesn't gets detected as a game by 2 apps (samsung game launcher and omlet arcade), i think this is to categorize the app as a game but in android tv
